### PR TITLE
Replace "Mac" with "macOS"

### PR DESCRIPTION
**Pull request by MasterKale**
This PR proposes a slight tweak to rename "Mac" to "macOS" as the OS has been called "macOS" since 2016.

### CODE REVIEW

**Comment by timcappalli** [comment]
It is not a general use of the OS name. The product is called "Chrome on Mac".

**Comment by MasterKale** [comment]
> It is not a general use of the OS name. The product is called "Chrome on Mac".

Is this documented somewhere?

**Comment by timcappalli** [comment]
https://support.google.com/chrome/answer/95346
https://support.google.com/chrome/a/answer/7550274?hl=en

image

(`for` and `on` get used interchangeably)

**Comment by MasterKale** [comment]
Oh sweet, TIL. Thanks for the links, I don't see a need for this PR anymore.

**Pull request closed without merging**
