### PR TITLE
Override MDS values with local aaguid.json

### PR DESCRIPTION
**Pull request by opotonniee**
Simple inversion of order when merging the 2 json values.
The PR also includes the updated combined json file. Note that the diffs from the previous version in the repo are not only related to this change, but also because the MDS data was updated since Dec 1, when this repo included it.

### CODE REVIEW

**Comment by timcappalli** [comment]
@aseigler does this look OK to you?

**Comment by aseigler** [comment]
Yes, totally makes sense to me.

**Comment by opotonniee** [comment]
Would you like me to do a new PR with only the modified line?

**Review by timcappalli — APPROVED** [review]

**Comment by timcappalli** [comment]
@opotonniee made the change directly to avoid the merge conflict. Thanks for this!

**Pull request closed without merging**
