### PR TITLE
Add Aurora TouchID agent

### PR DESCRIPTION
**Pull request by mjg59**
Used for internal TouchID passkey support

### CODE REVIEW

**Comment by timcappalli** [comment]
@mjg59 do you have a link to your product?

**Comment by mjg59** [comment]
No, it's purely internal code making use of the Apple TouchID sensor but it ends up being exposed to IdPs and disambiguating it would be helpful.

**Comment by timcappalli** [comment]
Unfortunately we're unable to add passkey providers without any public information.

**Comment by mjg59** [comment]
What level of public information is required?

**Comment by timcappalli** [comment]
A basic product information page would suffice. This list is not intended for private / same party providers. It is for mass market, publicly available passkey providers usable with any relying party.

**Comment by mjg59** [comment]
Ok, would you accept a PR to document that?

**Comment by timcappalli** [comment]
Normally I'd say yes, but this is going away shortly.

**Pull request closed without merging**
